### ISSUE TITLE
Communications settings SNS topic missing "Status"

### ISSUE THREAD

**Issue by madisettisunil** [trendmicro/terraform-provider-conformity#11]
the Configure Triggers option on the SNS topic is missing "Status". This leads to getting notifications of success and failure rules both. Having ability to switchoff success and only get notified for failure rules is highly deserable option.

**Comment by AmitChotaliya** [comment]
https://github.com/trendmicro/terraform-provider-conformity/blob/main/conformity/resource_conformity_communication_setting.go#L201
