### ISSUE TITLE
Support for region de-1

### ISSUE THREAD

**Issue by jbrmg** [trendmicro/terraform-provider-conformity#20]
Hi,

our account is located in region `de-1`. However, I cannot configure the Terraform provider with that region as `de-1` is not in the list of supported regions. Terraform returns the following error message:

`Error: expected region to be one of [eu-west-1 us-west-2 ap-southeast-2], got de-1`

Can you add support for the `de-1` region?

Thanks
Jan

**Comment by dsuraj221** [comment]
Hi @jbrmg 
This Issue Has been resolved.
