### ISSUE TITLE
conformity_azure_account: environment field should not be required

### ISSUE THREAD

**Issue by jbrmg** [trendmicro/terraform-provider-conformity#21]
The `environment` flag on `conformity_azure_account` is marked as required in the Terraform provider, but it is not required according to the API specification: https://cloudone.trendmicro.com/docs/conformity/api-reference/tag/Accounts#paths/~1accounts/post

This makes it difficult to import existing accounts without specified `environment` (requires a modification of the account which is not necessary).

**Comment by dsuraj221** [comment]
Hi @jbrmg,
 We have made the environment field is optional.
 Thanks
