### ISSUE TITLE
conformity_gcp_org: private_key exposed in logs.

### ISSUE THREAD

**Issue by jbrmg** [trendmicro/terraform-provider-conformity#28]
Hi,

the `private_key` field of the new resource `conformity_gcp_org` is not marked as `Senstive: true`. As a consequence of this, the private key is exposed in log files. Can you mark the field as `Sensitive` to protect its value?

**Comment by dsuraj221** [comment]
Hi @jbrmg 

Privet_key is sensitive now.

Thanks
